name: Deploy

on:
  push:
    branches: ["gh-pages"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-hostinger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload to Hostinger via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: 185.173.111.186
          username: u937190574.devocionalfilholiberto.shop
          password: ${{ secrets.FTP_PASSWORD }}
          remote_path: /public_html/
          local_path: ./*
          sftp_only: true
          port: 65002
          args: '-o StrictHostKeyChecking=no'
